version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: mongod --bind_ip_all

  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=healthcare
      - DOCKER_INFLUXDB_INIT_BUCKET=patient_measurements
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mysecrettoken
    volumes:
      - influxdb-data:/var/lib/influxdb2

  neo4j:
    image: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4j123
    volumes:
      - neo4j-data:/data

  redis-master:
    image: redis:7
    container_name: redis-master
    ports:
    - "16379:6379"


    volumes:
      - redis-data-master:/data
    command: redis-server --appendonly yes

  redis-replica:
    image: redis:7
    container_name: redis-replica
    depends_on:
      - redis-master
    ports:
      - "6380:6379"
    command: redis-server --replicaof redis-master 6379 --appendonly yes
    volumes:
      - redis-data-replica:/data

  cassandra:
    image: cassandra:4.0
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra

volumes:
  mongo-data:
  influxdb-data:
  neo4j-data:
  redis-data-master:
  redis-data-replica:
  cassandra-data:
